export enum ACTIVITY_CONSTANTS {
  LIKE_POST = "LIKE_POST",
  CREATE_POST = "CREATE_POST",
  COMMENT_POST = "COMMENT_POST",
  FOLLOW_USER = "FOLLOW_USER",
  REMOVE_LIKE_POST = "REMOVE_LIKE_POST",
  REMOVE_COMMENT_POST = "REMOVE_COMMENT_POST",
  REMOVE_FOLLOW_USER = "REMOVE_FOLLOW_USER",
  UPDATE_COMMENT_POST = "UPDATE_COMMENT_POST",
  REMOVE_POST = "REMOVE_POST",
}

export const ACTIVITY_CONSTANTS_ARRAY = [
  ACTIVITY_CONSTANTS.LIKE_POST,
  ACTIVITY_CONSTANTS.CREATE_POST,
  ACTIVITY_CONSTANTS.COMMENT_POST,
  ACTIVITY_CONSTANTS.FOLLOW_USER,
  ACTIVITY_CONSTANTS.REMOVE_LIKE_POST,
  ACTIVITY_CONSTANTS.REMOVE_COMMENT_POST,
  ACTIVITY_CONSTANTS.REMOVE_FOLLOW_USER,
  ACTIVITY_CONSTANTS.UPDATE_COMMENT_POST,
  ACTIVITY_CONSTANTS.REMOVE_POST,
];
